name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'
        cache: 'yarn'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: saucelabs/sauce-connect-action@v2
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_API_KEY }}
        tunnelIdentifier: github-action-tunnel
    - run: npm install -g yarn@1.22.10
    - run: yarn
    - run: yarn run build
    - run: yarn run test:quick
    - run: yarn run test:e2e:saucelabs
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_API_KEY }}
